
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import AnimatedLayout from "@/components/animated-layout";
import NewHeader from "@/components/new-header";
import NewSidebar from "@/components/new-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NewHeader />
          <div className="dashboard">
            <NewSidebar />
            <AnimatedLayout>{children}</AnimatedLayout>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}

